spring:
  main:
    allow-bean-definition-overriding : true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret_key: ${SECRET_KEY}
  access_exp: ${ACCESS_EXP}
  refresh_exp: ${REFRESH_EXP}
  header: ${HEADER}
  prefix: ${PREFIX}